ourRelease: 7.0.1
ourBranch: stable
gluonRelease: 2019.1
targets:
    - { target: ar71xx-generic, buildBroken: true }
    - { target: ar71xx-nand }
    - { target: ar71xx-tiny }
    - { target: brcm2708-bcm2708 }
    - { target: brcm2708-bcm2709 }
    - { target: ipq40xx }
    - { target: mpc85xx-generic }
    - { target: mpc85xx-p1020 }
    - { target: ramips-mt7620 }
    - { target: ramips-mt7621 }
    - { target: ramips-mt76x8 }
    - { target: ramips-rt305x }
    - { target: sunxi-cortexa7 }
    - { target: x86-64 }
    - { target: x86-generic }
    - { target: x86-geode }
