---

ourRelease: 8.1.0
ourBranch: stable
gluonRelease: 2020.2.1
targets:
    - { target: ar71xx-generic, arch: mips_24kc, buildBroken: true }
    - { target: ar71xx-nand, arch: mips_24kc }
    - { target: ar71xx-tiny, arch: mips_24kc }
    - { target: ath79-generic, arch: mips_24kc }
    - { target: brcm2708-bcm2708, arch: arm_arm1176jzf-s_vfp }
    - { target: brcm2708-bcm2709, arch: arm_cortex-a7_neon-vfpv4 }
    - { target: ipq40xx-generic, arch: arm_cortex-a7_neon-vfpv4 }
    - { target: ipq806x-generic, arch: arm_cortex-a15_neon-vfpv4 }
    - { target: lantiq-xrx200, arch: mips_24kc }
    - { target: lantiq-xway, arch: mips_24kc }
    - { target: mpc85xx-generic, arch: powerpc_8540 }
    - { target: mpc85xx-p1020, arch: powerpc_8540 }
    - { target: ramips-mt7620, arch: mipsel_24kc }
    - { target: ramips-mt7621, arch: mipsel_24kc }
    - { target: ramips-mt76x8, arch: mipsel_24kc }
    - { target: ramips-rt305x, arch: mipsel_24kc }
    - { target: sunxi-cortexa7, arch: arm_cortex-a7_neon-vfpv4 }
    - { target: x86-64, arch: x86_64 }
    - { target: x86-generic, arch: i386_pentium4 }
    - { target: x86-geode, arch: i386_pentium }
